# Generated by Django 2.1.7 on 2019-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBCdifferential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('LYMPHS_MAN_CNT', models.IntegerField()),
                ('MONOS_MAN_CNT', models.DecimalField(decimal_places=2, max_digits=2)),
                ('NEUTROPHILS_MAN_CNT', models.DecimalField(decimal_places=2, max_digits=2)),
                ('PLTS_MORPH', models.DecimalField(decimal_places=2, max_digits=2)),
                ('PLTs_BLD_QL_MAN', models.DecimalField(decimal_places=2, max_digits=2)),
                ('NEUTROPHILS_CALCULATED', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='Date',
            field=models.DateField(),
        ),
    ]
