# Generated by Django 2.1.7 on 2019-03-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaadata', '0002_auto_20190227_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbcresults',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='wbcdifferential',
            old_name='Date',
            new_name='date',
        ),
    ]
