# Generated by Django 2.1.7 on 2019-03-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaadata', '0003_auto_20190301_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbcresults',
            name='Platelets',
            field=models.IntegerField(),
        ),
    ]
