# Generated by Django 2.1.7 on 2019-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaadata', '0004_auto_20190302_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbcresults',
            name='MCV',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='NRBC',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
