# Generated by Django 2.1.7 on 2019-03-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaadata', '0005_auto_20190302_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbcresults',
            name='HCT_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='Hgb',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='MCV',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='NRBC',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='RBCs',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='RDW_RBC_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cbcresults',
            name='WBC',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
