# Generated by Django 2.1.7 on 2019-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaadata', '0006_auto_20190302_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcresults',
            name='user',
            field=models.CharField(default=99, max_length=50),
            preserve_default=False,
        ),
    ]
